[package]
name = "poll_rate_checker"
version = "0.1.0"
edition = "2024"


[dependencies.windows]
version = "0.61"
features = [
    "System",
    "Win32_Graphics_Gdi",
    "Win32_UI",
    "Win32_UI_WindowsAndMessaging",
    "Win32_System_LibraryLoader",
    "Win32_System_WinRT_Composition",
    "UI_Composition",
    "Win32_UI_Input",
    "Win32_UI_Input_Pointer",
    "UI_Composition_Desktop"
]

